# -*- coding: utf-8 -*-
"""Group 7 Google Merchandise Sales Data Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YB8rwTkjdm7DzPe56n9oWJ3j_OQgJQui
"""

from pyspark import SparkContext, SparkConf
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
from pyspark.sql.types import IntegerType
from pyspark.sql.functions import col, max as max_, when, count, avg, expr, explode
from pyspark.ml.recommendation import ALS
from pyspark.ml.evaluation import RegressionEvaluator
from pyspark.sql.functions import lit
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re

conf = SparkConf().setAppName('Google Merchandise Recommendation System')
sc = SparkContext.getOrCreate(conf = conf)

spark = SparkSession.builder\
        .master("local[*]") \
        .config("spark.driver.extraJavaOptions", "-Xss4M") \
        .config("spark.executor.extraJavaOptions", "-Xss4M") \
        .getOrCreate()

"""# **Importing Dataset**"""

events_df = spark.read.csv("data/events1.csv", header=True)
items_df = spark.read.csv("data/items.csv", header=True)
users_df = spark.read.csv("data/users.csv", header=True)

"""# **Data Pre-Processing**"""

#Dropping columns which are not required for recommendation
events_df = events_df.drop("ga_session_id").drop("date").drop("device")

items_df = items_df.drop("brand").drop("price_in_usd").drop("variant")
items_df = items_df.withColumnRenamed("id", "item_id")

final_df = events_df.join(items_df, on="item_id", how="inner")
final_df = final_df.withColumn('item_id', final_df['item_id'].cast(IntegerType()))
final_df = final_df.withColumn('user_id', final_df['user_id'].cast(IntegerType()))

# Checking NULL values
for column in final_df.columns:
    print(column,final_df.filter(col(column).isNull()).count())

final_df = final_df.dropna(subset=["country"])
final_df = final_df.dropDuplicates()

final_df.show(5)
final_df.count()

# Calculating Total interaction counts by grouping 'type',`'category', and 'country' columns
interaction_counts = final_df.groupBy("type","category","country").agg(count("*").alias("count"))

# Calculating maximum count across all
max_count = interaction_counts.agg(max_("count").alias("max_count")).collect()[0]["max_count"]

# Calculating and Normalizing weights by dividing the count by global maximum count
interaction_counts_with_weights = interaction_counts.withColumn(
    "weight",
    (col("count") / max_count)
)

#Updated interaction counts with weights
interaction_counts_with_weights.show()

#Joining calculated weights back to the final dataset
final_df = final_df.join(
    interaction_counts_with_weights.select("type", "category", "country", "weight"),
    on=["type", "category", "country"],
    how="left"
)

final_df.show()

ratings_df = final_df.select("user_id", "item_id", "weight") # Selecting from final_df instead of events_df
ratings_df.show()

# Splitting the ratings_df into training and test sets 75% and 25% respectively
(training_df, test_df) = ratings_df.randomSplit([0.75, 0.25])

#ALS model
als = ALS(
    userCol="user_id",
    itemCol="item_id",
    ratingCol="weight",
    coldStartStrategy="drop",
    nonnegative=True,
    rank=10,
    maxIter=15,
    regParam=0.1
)

# Fitting the model
model = als.fit(training_df)

# Predictions using test_df
predictions = model.transform(test_df)

predictions.show(5)

# Calculating RMSE to check model performance

evaluator = RegressionEvaluator(
    metricName="rmse",
    labelCol="weight",
    predictionCol="prediction"
)
# Computing RMSE for the model
rmse = evaluator.evaluate(predictions)

# Calculating average rating in the training set
average_rating = training_df.select(mean("weight").alias("avg_weight")).collect()[0]["avg_weight"]

# Creating a baseline prediction by assigning the average rating to all items in the test set
baseline_predictions = test_df.withColumn("prediction", lit(average_rating))

# Computing RMSE for the baseline
baseline_rmse = evaluator.evaluate(baseline_predictions)

print(f"Root-mean-square error (Model) = {rmse}")
print(f"Root-mean-square error (Baseline) = {baseline_rmse}")

# Generate top 10 recommendations for each user
user_recommendations = model.recommendForAllUsers(10)

# Flattening the recommendations DataFrame to remove already interacted items
interacted_items = final_df.select("user_id", "item_id").distinct()

flattened_recommendations = user_recommendations.select(
    col("user_id"),
    explode(col("recommendations")).alias("recommendation")
).select(
    col("user_id"),
    col("recommendation.item_id").alias("item_id"),
    col("recommendation.rating").alias("rating")
)

filtered_recommendations = flattened_recommendations.join(
    interacted_items,
    on=["user_id", "item_id"],
    how="left_anti"  # Keep only items not present in the interaction dataset
)

# Re-grouping the recommendations back to the original structure
final_recommendations = filtered_recommendations.groupBy("user_id").agg(
    expr("collect_list(struct(item_id, rating))").alias("recommendations")
)

# Final Recommendations
final_recommendations.show(truncate=False)

# Explode recommendations to get item_id and rating for all users
exploded_recommendations = user_recommendations.withColumn("recommendation", explode(col("recommendations"))) \
    .select("user_id", col("recommendation.item_id").alias("item_id"), col("recommendation.rating").alias("rating"))

# Calculate average rating for each item
average_ratings = exploded_recommendations.groupBy("item_id").agg(avg("rating").alias("average_rating"))

average_ratings_df = average_ratings.orderBy(col("average_rating").desc()).limit(10).toPandas()

# Bar chart
plt.figure(figsize=(10, 6))
plt.bar(average_ratings_df["item_id"].astype(str), average_ratings_df["average_rating"], color="coral")
plt.xlabel("Item ID")
plt.ylabel("Average Rating")
plt.title("Top 10 Items by Average Rating")
plt.xticks(rotation=45)
plt.show()


df_to_save = flattened_recommendations.toPandas()


df_to_save.to_csv("Final_Recommendation.csv", index=False)

print("Successfully saved recommendations to Final_Recommendation.csv!")

